name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if Git tag exists
      run: echo "HEAD_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
    - name: Install mops
      uses: ZenVoich/setup-mops@v1
    - name: "test"
      run: mops test
